const dex = require('@pkmn/dex');
const toID = dex.toID;
const Dex = dex.Dex;
const Generations = require('@pkmn/data').Generations;
const gens = new Generations(Dex);
const HMAJSON = require('./output.json');
const fs = require('fs');
const mons = [
    "Bulbasaur",
	"Ivysaur",
	"Venusaur",
	"Charmander",
	"Charmeleon",
	"Charizard",
	"Squirtle",
	"Wartortle",
	"Blastoise",
	"Caterpie",
	"Metapod",
	"Butterfree",
	"Weedle",
	"Kakuna",
	"Beedrill",
	"Pidgey",
	"Pidgeotto",
	"Pidgeot",
	"Rattata",
	"Raticate",
	"Spearow",
	"Fearow",
	"Ekans",
	"Arbok",
	"Pikachu",
	"Raichu",
	"Sandshrew",
	"Sandslash",
	"Nidoran\\sf",
	"Nidorina",
	"Nidoqueen",
	"Nidoran\\sm",
	"Nidorino",
	"Nidoking",
	"Clefairy",
	"Clefable",
	"Vulpix",
	"Ninetales",
	"Jigglypuff",
	"Wigglytuff",
	"Zubat",
	"Golbat",
	"Oddish",
	"Gloom",
	"Vileplume",
	"Paras",
	"Parasect",
	"Venonat",
	"Venomoth",
	"Diglett",
	"Dugtrio",
	"Meowth",
	"Persian",
	"Psyduck",
	"Golduck",
	"Mankey",
	"Primeape",
	"Growlithe",
	"Arcanine",
	"Poliwag",
	"Poliwhirl",
	"Poliwrath",
	"Abra",
	"Kadabra",
	"Alakazam",
	"Machop",
	"Machoke",
	"Machamp",
	"Bellsprout",
	"Weepinbell",
	"Victreebel",
	"Tentacool",
	"Tentacruel",
	"Geodude",
	"Graveler",
	"Golem",
	"Ponyta",
	"Rapidash",
	"Slowpoke",
	"Slowbro",
	"Magnemite",
	"Magneton",
	"Farfetch'd",
	"Doduo",
	"Dodrio",
	"Seel",
	"Dewgong",
	"Grimer",
	"Muk",
	"Shellder",
	"Cloyster",
	"Gastly",
	"Haunter",
	"Gengar",
	"Onix",
	"Drowzee",
	"Hypno",
	"Krabby",
	"Kingler",
	"Voltorb",
	"Electrode",
	"Exeggcute",
	"Exeggutor",
	"Cubone",
	"Marowak",
	"Hitmonlee",
	"Hitmonchan",
	"Lickitung",
	"Koffing",
	"Weezing",
	"Rhyhorn",
	"Rhydon",
	"Chansey",
	"Tangela",
	"Kangaskhan",
	"Horsea",
	"Seadra",
	"Goldeen",
	"Seaking",
	"Staryu",
	"Starmie",
	"Mr. Mime",
	"Scyther",
	"Jynx",
	"Electabuzz",
	"Magmar",
	"Pinsir",
	"Tauros",
	"Magikarp",
	"Gyarados",
	"Lapras",
	"Ditto",
	"Eevee",
	"Vaporeon",
	"Jolteon",
	"Flareon",
	"Porygon",
	"Omanyte",
	"Omastar",
	"Kabuto",
	"Kabutops",
	"Aerodactyl",
	"Snorlax",
	"Articuno",
	"Zapdos",
	"Moltres",
	"Dratini",
	"Dragonair",
	"Dragonite",
	"Mewtwo",
	"Mew",
	"Chikorita",
	"Bayleef",
	"Meganium",
	"Cyndaquil",
	"Quilava",
	"Typhlosion",
	"Totodile",
	"Croconaw",
	"Feraligatr",
	"Sentret",
	"Furret",
	"Hoothoot",
	"Noctowl",
	"Ledyba",
	"Ledian",
	"Spinarak",
	"Ariados",
	"Crobat",
	"Chinchou",
	"Lanturn",
	"Pichu",
	"Cleffa",
	"Igglybuff",
	"Togepi",
	"Togetic",
	"Natu",
	"Xatu",
	"Mareep",
	"Flaaffy",
	"Ampharos",
	"Bellossom",
	"Marill",
	"Azumarill",
	"Sudowoodo",
	"Politoed",
	"Hoppip",
	"Skiploom",
	"Jumpluff",
	"Aipom",
	"Sunkern",
	"Sunflora",
	"Yanma",
	"Wooper",
	"Quagsire",
	"Espeon",
	"Umbreon",
	"Murkrow",
	"Slowking",
	"Misdreavus",
	"Unown",
	"Wobbuffet",
	"Girafarig",
	"Pineco",
	"Forretress",
	"Dunsparce",
	"Gligar",
	"Steelix",
	"Snubbull",
	"Granbull",
	"Qwilfish",
	"Scizor",
	"Shuckle",
	"Heracross",
	"Sneasel",
	"Teddiursa",
	"Ursaring",
	"Slugma",
	"Magcargo",
	"Swinub",
	"Piloswine",
	"Corsola",
	"Remoraid",
	"Octillery",
	"Delibird",
	"Mantine",
	"Skarmory",
	"Houndour",
	"Houndoom",
	"Kingdra",
	"Phanpy",
	"Donphan",
	"Porygon2",
	"Stantler",
	"Smeargle",
	"Tyrogue",
	"Hitmontop",
	"Smoochum",
	"Elekid",
	"Magby",
	"Miltank",
	"Blissey",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Pupitar",
	"Tyranitar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"Treecko",
	"Grovyle",
	"Sceptile",
	"Torchic",
	"Combusken",
	"Blaziken",
	"Mudkip",
	"Marshtomp",
	"Swampert",
	"Poochyena",
	"Mightyena",
	"Zigzagoon",
	"Linoone",
	"Wurmple",
	"Silcoon",
	"Beautifly",
	"Cascoon",
	"Dustox",
	"Lotad",
	"Lombre",
	"Ludicolo",
	"Seedot",
	"Nuzleaf",
	"Shiftry",
	"Taillow",
	"Swellow",
	"Wingull",
	"Pelipper",
	"Ralts",
	"Kirlia",
	"Gardevoir",
	"Surskit",
	"Masquerain",
	"Shroomish",
	"Breloom",
	"Slakoth",
	"Vigoroth",
	"Slaking",
	"Nincada",
	"Ninjask",
	"Shedinja",
	"Whismur",
	"Loudred",
	"Exploud",
	"Makuhita",
	"Hariyama",
	"Azurill",
	"Nosepass",
	"Skitty",
	"Delcatty",
	"Sableye",
	"Mawile",
	"Aron",
	"Lairon",
	"Aggron",
	"Meditite",
	"Medicham",
	"Electrike",
	"Manectric",
	"Plusle",
	"Minun",
	"Volbeat",
	"Illumise",
	"Roselia",
	"Gulpin",
	"Swalot",
	"Carvanha",
	"Sharpedo",
	"Wailmer",
	"Wailord",
	"Numel",
	"Camerupt",
	"Torkoal",
	"Spoink",
	"Grumpig",
	"Spinda",
	"Trapinch",
	"Vibrava",
	"Flygon",
	"Cacnea",
	"Cacturne",
	"Swablu",
	"Altaria",
	"Zangoose",
	"Seviper",
	"Lunatone",
	"Solrock",
	"Barboach",
	"Whiscash",
	"Corphish",
	"Crawdaunt",
	"Baltoy",
	"Claydol",
	"Lileep",
	"Cradily",
	"Anorith",
	"Armaldo",
	"Feebas",
	"Milotic",
	"Castform",
	"Kecleon",
	"Shuppet",
	"Banette",
	"Duskull",
	"Dusclops",
	"Tropius",
	"Chimecho",
	"Absol",
	"Wynaut",
	"Snorunt",
	"Glalie",
	"Spheal",
	"Sealeo",
	"Walrein",
	"Clamperl",
	"Huntail",
	"Gorebyss",
	"Relicanth",
	"Luvdisc",
	"Bagon",
	"Shelgon",
	"Salamence",
	"Beldum",
	"Metang",
	"Metagross",
	"Regirock",
	"Regice",
	"Registeel",
	"Latias",
	"Latios",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Jirachi",
	"Deoxys",
	"Turtwig",
	"Grotle",
	"Torterra",
	"Chimchar",
	"Monferno",
	"Infernape",
	"Piplup",
	"Prinplup",
	"Empoleon",
	"Starly",
	"Staravia",
	"Staraptor",
	"Bidoof",
	"Bibarel",
	"Kricketot",
	"Kricketune",
	"Shinx",
	"Luxio",
	"Luxray",
	"Budew",
	"Roserade",
	"Cranidos",
	"Rampardos",
	"Shieldon",
	"Bastiodon",
	"Burmy",
	"Wormadam",
	"Mothim",
	"Combee",
	"Vespiquen",
	"Pachirisu",
	"Buizel",
	"Floatzel",
	"Cherubi",
	"Cherrim",
	"Shellos",
	"Gastrodon",
	"Ambipom",
	"Drifloon",
	"Drifblim",
	"Buneary",
	"Lopunny",
	"Mismagius",
	"Honchkrow",
	"Glameow",
	"Purugly",
	"Chingling",
	"Stunky",
	"Skuntank",
	"Bronzor",
	"Bronzong",
	"Bonsly",
	"Mime Jr.",
	"Happiny",
	"Chatot",
	"Spiritomb",
	"Gible",
	"Gabite",
	"Garchomp",
	"Munchlax",
	"Riolu",
	"Lucario",
	"Hippopotas",
	"Hippowdon",
	"Skorupi",
	"Drapion",
	"Croagunk",
	"Toxicroak",
	"Carnivine",
	"Finneon",
	"Lumineon",
	"Mantyke",
	"Snover",
	"Abomasnow",
	"Weavile",
	"Magnezone",
	"Lickilicky",
	"Rhyperior",
	"Tangrowth",
	"Electivire",
	"Magmortar",
	"Togekiss",
	"Yanmega",
	"Leafeon",
	"Glaceon",
	"Gliscor",
	"Mamoswine",
	"Porygon-Z",
	"Gallade",
	"Probopass",
	"Dusknoir",
	"Froslass",
	"Rotom",
	"Uxie",
	"Mesprit",
	"Azelf",
	"Dialga",
	"Palkia",
	"Heatran",
	"Regigigas",
	"Giratina",
	"Cresselia",
	"Phione",
	"Manaphy",
	"Darkrai",
	"Shaymin",
	"Arceus",
	"Victini",
	"Snivy",
	"Servine",
	"Serperior",
	"Tepig",
	"Pignite",
	"Emboar",
	"Oshawott",
	"Dewott",
	"Samurott",
	"Patrat",
	"Watchog",
	"Lillipup",
	"Herdier",
	"Stoutland",
	"Purrloin",
	"Liepard",
	"Pansage",
	"Simisage",
	"Pansear",
	"Simisear",
	"Panpour",
	"Simipour",
	"Munna",
	"Musharna",
	"Pidove",
	"Tranquill",
	"Unfezant",
	"Blitzle",
	"Zebstrika",
	"Roggenrola",
	"Boldore",
	"Gigalith",
	"Woobat",
	"Swoobat",
	"Drilbur",
	"Excadrill",
	"Audino",
	"Timburr",
	"Gurdurr",
	"Conkeldurr",
	"Tympole",
	"Palpitoad",
	"Seismitoad",
	"Throh",
	"Sawk",
	"Sewaddle",
	"Swadloon",
	"Leavanny",
	"Venipede",
	"Whirlipede",
	"Scolipede",
	"Cottonee",
	"Whimsicott",
	"Petilil",
	"Lilligant",
	"Basculin",
	"Sandile",
	"Krokorok",
	"Krookodile",
	"Darumaka",
	"Darmanitan",
	"Maractus",
	"Dwebble",
	"Crustle",
	"Scraggy",
	"Scrafty",
	"Sigilyph",
	"Yamask",
	"Cofagrigus",
	"Tirtouga",
	"Carracosta",
	"Archen",
	"Archeops",
	"Trubbish",
	"Garbodor",
	"Zorua",
	"Zoroark",
	"Minccino",
	"Cinccino",
	"Gothita",
	"Gothorita",
	"Gothitelle",
	"Solosis",
	"Duosion",
	"Reuniclus",
	"Ducklett",
	"Swanna",
	"Vanillite",
	"Vanillish",
	"Vanilluxe",
	"Deerling",
	"Sawsbuck",
	"Emolga",
	"Karrablast",
	"Escavalier",
	"Foongus",
	"Amoonguss",
	"Frillish",
	"Jellicent",
	"Alomomola",
	"Joltik",
	"Galvantula",
	"Ferroseed",
	"Ferrothorn",
	"Klink",
	"Klang",
	"Klinklang",
	"Tynamo",
	"Eelektrik",
	"Eelektross",
	"Elgyem",
	"Beheeyem",
	"Litwick",
	"Lampent",
	"Chandelure",
	"Axew",
	"Fraxure",
	"Haxorus",
	"Cubchoo",
	"Beartic",
	"Cryogonal",
	"Shelmet",
	"Accelgor",
	"Stunfisk",
	"Mienfoo",
	"Mienshao",
	"Druddigon",
	"Golett",
	"Golurk",
	"Pawniard",
	"Bisharp",
	"Bouffalant",
	"Rufflet",
	"Braviary",
	"Vullaby",
	"Mandibuzz",
	"Heatmor",
	"Durant",
	"Deino",
	"Zweilous",
	"Hydreigon",
	"Larvesta",
	"Volcarona",
	"Cobalion",
	"Terrakion",
	"Virizion",
	"Tornadus",
	"Thundurus",
	"Reshiram",
	"Zekrom",
	"Landorus",
	"Kyurem",
	"Keldeo",
	"Meloetta",
	"Genesect",
	"Chespin",
	"Quilladin",
	"Chesnaught",
	"Fennekin",
	"Braixen",
	"Delphox",
	"Froakie",
	"Frogadier",
	"Greninja",
	"Bunnelby",
	"Diggersby",
	"Fletchling",
	"Flechinder",
	"Talonflame",
	"Scatterbug",
	"Spewpa",
	"Vivillon",
	"Litleo",
	"Pyroar",
	"Flabébé",
	"Floette",
	"Florges",
	"Skiddo",
	"Gogoat",
	"Pancham",
	"Pangoro",
	"Furfrou",
	"Espurr",
	"Meowstic",
	"Honedge",
	"Doublade",
	"Aegislash",
	"Spritzee",
	"Aromatisse",
	"Swirlix",
	"Slurpuff",
	"Inkay",
	"Malamar",
	"Binacle",
	"Barbaracle",
	"Skrelp",
	"Dragalge",
	"Clauncher",
	"Clawitzer",
	"Helioptile",
	"Heliolisk",
	"Tyrunt",
	"Tyrantrum",
	"Amaura",
	"Aurorus",
	"Sylveon",
	"Hawlucha",
	"Dedenne",
	"Carbink",
	"Goomy",
	"Sliggoo",
	"Goodra",
	"Klefki",
	"Phantump",
	"Trevenant",
	"Pumpkaboo",
	"Gourgeist",
	"Bergmite",
	"Avalugg",
	"Noibat",
	"Noivern",
	"Xerneas",
	"Yveltal",
	"Zygarde",
	"Diancie",
	"Hoopa",
	"Volcanion",
	"Rowlet",
	"Dartrix",
	"Decidueye",
	"Litten",
	"Torracat",
	"Incineroar",
	"Popplio",
	"Brionne",
	"Primarina",
	"Pikipek",
	"Trumbeak",
	"Toucannon",
	"Yungoos",
	"Gumshoos",
	"Grubbin",
	"Charjabug",
	"Vikavolt",
	"Crabrawler",
	"Crabminabl",
	"Oricorio",
	"Cutiefly",
	"Ribombee",
	"Rockruff",
	"Lycanroc",
	"Wishiwashi",
	"Mareanie",
	"Toxapex",
	"Mudbray",
	"Mudsdale",
	"Dewpider",
	"Araquanid",
	"Fomantis",
	"Lurantis",
	"Morelull",
	"Shiinotic",
	"Salandit",
	"Salazzle",
	"Stufful",
	"Bewear",
	"Bounsweet",
	"Steenee",
	"Tsareena",
	"Comfey",
	"Oranguru",
	"Passimian",
	"Wimpod",
	"Golisopod",
	"Sandygast",
	"Palossand",
	"Pyukumuku",
	"Type: Null",
	"Silvally",
	"Minior",
	"Komala",
	"Turtonator",
	"Togedemaru",
	"Mimikyu",
	"Bruxish",
	"Drampa",
	"Dhelmise",
	"Jangmo-o",
	"Hakamo-o",
	"Kommo-o",
	"Tapu Koko",
	"Tapu Lele",
	"Tapu Bulu",
	"Tapu Fini",
	"Cosmog",
	"Cosmoem",
	"Solgaleo",
	"Lunala",
	"Nihilego",
	"Buzzwole",
	"Pheromosa",
	"Xurkitree",
	"Celesteela",
	"Kartana",
	"Guzzlord",
	"Necrozma",
	"Magearna",
	"Marshadow",
	"Poipole",
	"Naganadel",
	"Stakataka",
	"Blacephaln",
	"Zeraora",
	"Meltan",
	"Melmetal",
	"Grookey",
	"Thwackey",
	"Rillaboom",
	"Scorbunny",
	"Raboot",
	"Cinderace",
	"Sobble",
	"Drizzile",
	"Inteleon",
	"Skwovet",
	"Greedent",
	"Rookidee",
	"Corvisquir",
	"Corviknigh",
	"Blipbug",
	"Dottler",
	"Orbeetle",
	"Nickit",
	"Thievul",
	"Gossifleur",
	"Eldegoss",
	"Wooloo",
	"Dubwool",
	"Chewtle",
	"Drednaw",
	"Yamper",
	"Boltund",
	"Rolycoly",
	"Carkol",
	"Coalossal",
	"Applin",
	"Flapple",
	"Appletun",
	"Silicobra",
	"Sandaconda",
	"Cramorant",
	"Arrokuda",
	"Barraskewd",
	"Toxel",
	"Toxtricity",
	"Sizzlipede",
	"Centiskorc",
	"Clobbopus",
	"Grapploct",
	"Sinistea",
	"Polteageis",
	"Hatenna",
	"Hattrem",
	"Hatterene",
	"Impidimp",
	"Morgrem",
	"Grimmsnarl",
	"Obstagoon",
	"Perrserker",
	"Cursola",
	"Sirfetch'd",
	"Mr. Rime",
	"Runerigus",
	"Milcery",
	"Alcremie",
	"Falinks",
	"Pincurchin",
	"Snom",
	"Frosmoth",
	"Stonjourne",
	"Eiscue",
	"Indeedee",
	"Morpeko",
	"Cufant",
	"Copperajah",
	"Dracozolt",
	"Arctozolt",
	"Dracovish",
	"Arctovish",
	"Duraludon",
	"Dreepy",
	"Drakloak",
	"Dragapult",
	"Zacian",
	"Zamazenta",
	"Eternatus",
	"Kubfu",
	"Urshifu",
	"Zarude",
	"Regieleki",
	"Regidrago",
	"Glastrier",
	"Spectrier",
	"Calyrex",
	"Wyrdeer",
	"Kleavor",
	"Ursaluna",
	"Bsculegion",
	"Sneasler",
	"Overqwil",
	"Enamorus",
	"Venusaur2",
	"Charizard2",
	"Charizard3",
	"Blastoise2",
	"Beedrill2",
	"Pidgeot2",
	"Alakazam2",
	"Slowbro2",
	"Gengar2",
	"Kangaskhan2",
	"Pinsir2",
	"Gyarados2",
	"Aerodactyl2",
	"Mewtwo2",
	"Mewtwo3",
	"Ampharos2",
	"Steelix2",
	"Scizor2",
	"Heracross2",
	"Houndoom2",
	"Tyranitar2",
	"Sceptile2",
	"Blaziken2",
	"Swampert2",
	"Gardevoir2",
	"Sableye2",
	"Mawile2",
	"Aggron2",
	"Medicham2",
	"Manectric2",
	"Sharpedo2",
	"Camerupt2",
	"Altaria2",
	"Banette2",
	"Absol2",
	"Glalie2",
	"Salamence2",
	"Metagross2",
	"Latias2",
	"Latios2",
	"Lopunny2",
	"Garchomp2",
	"Lucario2",
	"Abomasnow2",
	"Gallade2",
	"Audino2",
	"Diancie2",
	"Rayquaza2",
	"Kyogre2",
	"Groudon2",
	"Rattata2",
	"Raticate2",
	"Raichu2",
	"Sandshrew2",
	"Sandslash2",
	"Vulpix2",
	"Ninetales2",
	"Diglett2",
	"Dugtrio2",
	"Meowth2",
	"Persian2",
	"Geodude2",
	"Graveler2",
	"Golem2",
	"Grimer2",
	"Muk2",
	"Exeggutor2",
	"Marowak2",
	"Meowth3",
	"Ponyta2",
	"Rapidash2",
	"Slowpoke2",
	"Slowbro3",
	"Farfetch'd2",
	"Weezing2",
	"Mr. Mime2",
	"Articuno2",
	"Zapdos2",
	"Moltres2",
	"Slowking2",
	"Corsola2",
	"Zigzagoon2",
	"Linoone2",
	"Darumaka2",
	"Darmanitan2",
	"Yamask2",
	"Stunfisk2",
	"Growlithe2",
	"Arcanine2",
	"Voltorb2",
	"Electrode2",
	"Typhlosion2",
	"Qwilfish2",
	"Sneasel2",
	"Samurott2",
	"Lilligant2",
	"Zorua2",
	"Zoroark2",
	"Braviary2",
	"Sliggoo2",
	"Goodra2",
	"Avalugg2",
	"Decidueye2",
	"Pikachu2",
	"Pikachu3",
	"Pikachu4",
	"Pikachu5",
	"Pikachu6",
	"Pikachu7",
	"Pikachu8",
	"Pikachu9",
	"Pikachu10",
	"Pikachu11",
	"Pikachu12",
	"Pikachu13",
	"Pikachu14",
	"Pikachu15",
	"Pichu2",
	"Unown2",
	"Unown3",
	"Unown4",
	"Unown5",
	"Unown6",
	"Unown7",
	"Unown8",
	"Unown9",
	"Unown10",
	"Unown11",
	"Unown12",
	"Unown13",
	"Unown14",
	"Unown15",
	"Unown16",
	"Unown17",
	"Unown18",
	"Unown19",
	"Unown20",
	"Unown21",
	"Unown22",
	"Unown23",
	"Unown24",
	"Unown25",
	"Unown26",
	"Unown27",
	"Unown28",
	"Castform2",
	"Castform3",
	"Castform4",
	"Deoxys2",
	"Deoxys3",
	"Deoxys4",
	"Burmy2",
	"Burmy3",
	"Wormadam2",
	"Wormadam3",
	"Cherrim2",
	"Shellos2",
	"Gastrodon2",
	"Rotom2",
	"Rotom3",
	"Rotom4",
	"Rotom5",
	"Rotom6",
	"Dialga2",
	"Palkia2",
	"Giratina2",
	"Shaymin2",
	"Arceus2",
	"Arceus3",
	"Arceus4",
	"Arceus5",
	"Arceus6",
	"Arceus7",
	"Arceus8",
	"Arceus9",
	"Arceus10",
	"Arceus11",
	"Arceus12",
	"Arceus13",
	"Arceus14",
	"Arceus15",
	"Arceus16",
	"Arceus17",
	"Arceus18",
	"Basculin2",
	"Basculin3",
	"Darmanitan3",
	"Darmanitan4",
	"Deerling2",
	"Deerling3",
	"Deerling4",
	"Sawsbuck2",
	"Sawsbuck3",
	"Sawsbuck4",
	"Tornadus2",
	"Thundurus2",
	"Landorus2",
	"Enamorus2",
	"Kyurem2",
	"Kyurem3",
	"Keldeo2",
	"Meloetta2",
	"Genesect2",
	"Genesect3",
	"Genesect4",
	"Genesect5",
	"Greninja2",
	"Greninja3",
	"Vivillon2",
	"Vivillon3",
	"Vivillon4",
	"Vivillon5",
	"Vivillon6",
	"Vivillon7",
	"Vivillon8",
	"Vivillon9",
	"Vivillon10",
	"Vivillon11",
	"Vivillon12",
	"Vivillon13",
	"Vivillon14",
	"Vivillon15",
	"Vivillon16",
	"Vivillon17",
	"Vivillon18",
	"Vivillon19",
	"Vivillon20",
	"Flabébé2",
	"Flabébé3",
	"Flabébé4",
	"Flabébé5",
	"Floette2",
	"Floette3",
	"Floette4",
	"Floette5",
	"Floette6",
	"Florges2",
	"Florges3",
	"Florges4",
	"Florges5",
	"Furfrou2",
	"Furfrou3",
	"Furfrou4",
	"Furfrou5",
	"Furfrou6",
	"Furfrou7",
	"Furfrou8",
	"Furfrou9",
	"Furfrou10",
	"Meowstic2",
	"Aegislash2",
	"Pumpkaboo2",
	"Pumpkaboo3",
	"Pumpkaboo4",
	"Gourgeist2",
	"Gourgeist3",
	"Gourgeist4",
	"Xerneas2",
	"Zygarde2",
	"Zygarde3",
	"Zygarde4",
	"Zygarde5",
	"Hoopa2",
	"Oricorio2",
	"Oricorio3",
	"Oricorio4",
	"Rockruff2",
	"Lycanroc2",
	"Lycanroc3",
	"Wishiwashi2",
	"Silvally2",
	"Silvally3",
	"Silvally4",
	"Silvally5",
	"Silvally6",
	"Silvally7",
	"Silvally8",
	"Silvally9",
	"Silvally10",
	"Silvally11",
	"Silvally12",
	"Silvally13",
	"Silvally14",
	"Silvally15",
	"Silvally16",
	"Silvally17",
	"Silvally18",
	"Minior2",
	"Minior3",
	"Minior4",
	"Minior5",
	"Minior6",
	"Minior7",
	"Minior8",
	"Minior9",
	"Minior10",
	"Minior11",
	"Minior12",
	"Minior13",
	"Minior14",
	"Mimikyu2",
	"Necrozma2",
	"Necrozma3",
	"Necrozma4",
	"Magearna2",
	"Cramorant2",
	"Cramorant3",
	"Toxtricity2",
	"Sinistea2",
	"Polteageis2",
	"Alcremie2",
	"Alcremie3",
	"Alcremie4",
	"Alcremie5",
	"Alcremie6",
	"Alcremie7",
	"Alcremie8",
	"Alcremie9",
	"Eiscue2",
	"Indeedee2",
	"Morpeko2",
	"Zacian2",
	"Zamazenta2",
	"Eternatus2",
	"Urshifu2",
	"Zarude2",
	"Calyrex2",
	"Calyrex3",
	"Bsculegion2",
	"Alcremie10",
	"Alcremie11",
	"Alcremie12",
	"Alcremie13",
	"Alcremie14",
	"Alcremie15",
	"Alcremie16",
	"Alcremie17",
	"Alcremie18",
	"Alcremie19",
	"Alcremie20",
	"Alcremie21",
	"Alcremie22",
	"Alcremie23",
	"Alcremie24",
	"Alcremie25",
	"Alcremie26",
	"Alcremie27",
	"Alcremie28",
	"Alcremie29",
	"Alcremie30",
	"Alcremie31",
	"Alcremie32",
	"Alcremie33",
	"Alcremie34",
	"Alcremie35",
	"Alcremie36",
	"Alcremie37",
	"Alcremie38",
	"Alcremie39",
	"Alcremie40",
	"Alcremie41",
	"Alcremie42",
	"Alcremie43",
	"Alcremie44",
	"Alcremie45",
	"Alcremie46",
	"Alcremie47",
	"Alcremie48",
	"Alcremie49",
	"Alcremie50",
	"Alcremie51",
	"Alcremie52",
	"Alcremie53",
	"Alcremie54",
	"Alcremie55",
	"Alcremie56",
	"Alcremie57",
	"Alcremie58",
	"Alcremie59",
	"Alcremie60",
	"Alcremie61",
	"Alcremie62",
	"Alcremie63",
	"Sprigatito",
	"Floragato",
	"Meowscarad",
	"Fuecoco",
	"Crocalor",
	"Skeledirge",
	"Quaxly",
	"Quaxwell",
	"Quaquaval",
	"Lechonk",
	"Oinkologne",
	"Oinkologne2",
	"Tarountula",
	"Spidops",
	"Nymble",
	"Lokix",
	"Pawmi",
	"Pawmo",
	"Pawmot",
	"Tandemaus",
	"Maushold",
	"Maushold2",
	"Fidough",
	"Dachsbun",
	"Smoliv",
	"Dolliv",
	"Arboliva",
	"Sqawkabily",
	"Sqawkabily2",
	"Sqawkabily3",
	"Sqawkabily4",
	"Nacli",
	"Naclstack",
	"Garganacl",
	"Charcadet",
	"Armarouge",
	"Ceruledge",
	"Tadbulb",
	"Bellibolt",
	"Wattrel",
	"Kilowatrel",
	"Maschiff",
	"Mabosstiff",
	"Shroodle",
	"Grafaiai",
	"Bramblin",
	"Brmblghast",
	"Toedscool",
	"Toedscruel",
	"Klawf",
	"Capsakid",
	"Scovillain",
	"Rellor",
	"Rabsca",
	"Flittle",
	"Espathra",
	"Tinkatink",
	"Tinkatuff",
	"Tinkaton",
	"Wiglett",
	"Wugtrio",
	"Bombirdier",
	"Finizen",
	"Palafin",
	"Palafin2",
	"Varoom",
	"Revavroom",
	"Cyclizar",
	"Orthworm",
	"Glimmet",
	"Glimmora",
	"Greavard",
	"Houndstone",
	"Flamigo",
	"Cetoddle",
	"Cetitan",
	"Veluza",
	"Dondozo",
	"Tatsugiri",
	"Tatsugiri2",
	"Tatsugiri3",
	"Annihilape",
	"Clodsire",
	"Farigiraf",
	"Dudunsprce",
	"Dudunsprce2",
	"Kingambit",
	"Great Tusk",
	"ScreamTail",
	"BruteBonet",
	"FluttrMane",
	"SlithrWing",
	"SndyShocks",
	"IronTreads",
	"IronBundle",
	"Iron Hands",
	"IronJuguls",
	"Iron Moth",
	"IronThorns",
	"Frigibax",
	"Arctibax",
	"Baxcalibur",
	"Gimmighoul",
	"Gimmighoul2",
	"Gholdengo",
	"Wo-Chien",
	"Chien-Pao",
	"Ting-Lu",
	"Chi-Yu",
	"RoarngMoon",
	"IronVliant",
	"Koraidon",
	"Miraidon",
	"Tauros2",
	"Tauros3",
	"Tauros4",
	"Wooper2",
	"WalkngWake",
	"IronLeaves",
	"Dipplin",
	"Ptchageist",
	"Ptchageist2",
	"Sinistcha",
	"Sinistcha2",
	"Okidogi",
	"Munkidori",
	"Fezndipiti",
	"Ogerpon",
	"Ogerpon2",
	"Ogerpon3",
	"Ogerpon4",
	"Ogerpon5",
	"Ogerpon6",
	"Ogerpon7",
	"Ogerpon8",
	"Ursaluna2",
	"Archaludon",
	"Hydrapple",
	"GouginFire",
	"RagingBolt",
	"IronBouldr",
	"Iron Crown",
	"Terapagos",
	"Terapagos2",
	"Terapagos3",
	"Pecharunt",
	"Mothim2",
	"Mothim3",
	"Scatterbug2",
	"Scatterbug3",
	"Scatterbug4",
	"Scatterbug5",
	"Scatterbug6",
	"Scatterbug7",
	"Scatterbug8",
	"Scatterbug9",
	"Scatterbug10",
	"Scatterbug11",
	"Scatterbug12",
	"Scatterbug13",
	"Scatterbug14",
	"Scatterbug15",
	"Scatterbug16",
	"Scatterbug17",
	"Scatterbug18",
	"Scatterbug19",
	"Scatterbug20",
	"Spewpa2",
	"Spewpa3",
	"Spewpa4",
	"Spewpa5",
	"Spewpa6",
	"Spewpa7",
	"Spewpa8",
	"Spewpa9",
	"Spewpa10",
	"Spewpa11",
	"Spewpa12",
	"Spewpa13",
	"Spewpa14",
	"Spewpa15",
	"Spewpa16",
	"Spewpa17",
	"Spewpa18",
	"Spewpa19",
	"Spewpa20",
	"Raticate3",
	"Gumshoos2",
	"Vikavolt2",
	"Lurantis2",
	"Salazzle2",
	"Mimikyu3",
	"Kommo-o2",
	"Marowak3",
	"Ribombee2",
	"Araquanid2",
	"Togedemaru2",
	"Pikachu16",
	"Eevee2",
	"Venusaur3",
	"Blastoise3",
	"Charizard4",
	"Butterfree2",
	"Pikachu17",
	"Meowth4",
	"Machamp2",
	"Gengar3",
	"Kingler2",
	"Lapras2",
	"Eevee3",
	"Snorlax2",
	"Garbodor2",
	"Melmetal2",
	"Rillaboom2",
	"Cinderace2",
	"Inteleon2",
	"Corviknigh2",
	"Orbeetle2",
	"Drednaw2",
	"Coalossal2",
	"Flapple2",
	"Appletun2",
	"Sandaconda2",
	"Toxtricity3",
	"Toxtricity4",
	"Centiskorc2",
	"Hatterene2",
	"Grimmsnarl2",
	"Alcremie64",
	"Copperajah2",
	"Duraludon2",
	"Urshifu3",
	"Urshifu4",
	"Mimikyu4"
]
const movetutormoves = [
	'megapunch',
	'swordsdance',
	'megakick',
	'bodyslam',
	'doubleedge',
	'counter',
	'seismictoss',
	'mimic',
	'metronome',
	'softboiled',
	'dreameater',
	'thunderwave',
	'explosion',
	'rockslide',
	'substitute',
	// 'frenzyplant',
    // 'blastburn',
    // 'hydrocannon'
]
const tms = [
    'focuspunch',
    'dragonclaw',
    'waterpulse',
    'calmmind',
    'roar',
    'toxic',
    'hail',
    'bulkup',
    'bulletseed',
    'hiddenpower',
    'sunnyday',
    'taunt',
    'icebeam',
    'blizzard',
    'hyperbeam',
    'lightscreen',
    'protect',
    'raindance',
    'gigadrain',
    'safeguard',
    'frustration',
    'solarbeam',
    'irontail',
    'thunderbolt',
    'thunder',
    'earthquake',
    'return',
    'dig',
    'psychic',
    'shadowball',
    'brickbreak',
    'doubleteam',
    'reflect',
    'shockwave',
    'flamethrower',
    'sludgebomb',
    'sandstorm',
    'fireblast',
    'rocktomb',
    'aerialace',
    'torment',
    'facade',
    'secretpower',
    'rest',
    'attract',
    'thief',
    'steelwing',
    'skillswap',
    'snatch',
    'overheat',
    'cut',
    'fly',
    'surf',
    'strength',
    'flash',
    'rocksmash',
    'waterfall',
    'dive',
]
const items = [
    "????????",
    "Poké Ball",
    "Great Ball",
    "Ultra Ball",
    "Master Ball",
    "Premier Ball",
    "Heal Ball",
    "Net Ball",
    "Nest Ball",
    "Dive Ball",
    "Dusk Ball",
    "Timer Ball",
    "Quick Ball",
    "Repeat Ball",
    "Luxury Ball",
    "Level Ball",
    "Lure Ball",
    "Moon Ball",
    "Friend Ball",
    "Love Ball",
    "Fast Ball",
    "Heavy Ball",
    "Dream Ball",
    "Safari Ball",
    "Sport Ball",
    "Park Ball",
    "Beast Ball",
    "Cherish Ball",
    "Potion",
    "Super Potion",
    "Hyper Potion",
    "Max Potion",
    "Full Restore",
    "Revive",
    "Max Revive",
    "Fresh Water",
    "Soda Pop",
    "Lemonade",
    "Moomoo Milk",
    "Energy Powder",
    "Energy Root",
    "Heal Powder",
    "Revival Herb",
    "Antidote",
    "Paralyze Heal",
    "Burn Heal",
    "Ice Heal",
    "Awakening",
    "Full Heal",
    "Ether",
    "Max Ether",
    "Elixir",
    "Max Elixir",
    "Berry Juice",
    "Sacred Ash",
    "Sweet Heart",
    "Max Honey",
    "PewtrCrnches",
    "RageCandyBar",
    "Lava Cookie",
    "Old Gateau",
    "Casteliacone",
    "LumioseGlete",
    "ShalourSable",
    "Big Malasada",
    "HP Up",
    "Protein",
    "Iron",
    "Calcium",
    "Zinc",
    "Carbos",
    "PP Up",
    "PP Max",
    "HealthFeather",
    "MuscleFeather",
    "ResistFeather",
    "GeniusFeather",
    "CleverFeather",
    "SwiftFeather",
    "AbilityCapsle",
    "AbilityPatch",
    "Lonely Mint",
    "Adamant Mint",
    "Naughty Mint",
    "Brave Mint",
    "Bold Mint",
    "Impish Mint",
    "Lax Mint",
    "Relaxed Mint",
    "Modest Mint",
    "Mild Mint",
    "Rash Mint",
    "Quiet Mint",
    "Calm Mint",
    "Gentle Mint",
    "Careful Mint",
    "Sassy Mint",
    "Timid Mint",
    "Hasty Mint",
    "Jolly Mint",
    "Naive Mint",
    "Serious Mint",
    "Rare Candy",
    "Exp.Candy XS",
    "Exp.Candy S",
    "Exp.Candy M",
    "Exp.Candy L",
    "Exp.Candy XL",
    "DynamaxCandy",
    "Blue Flute",
    "Yellow Flute",
    "Red Flute",
    "Black Flute",
    "White Flute",
    "Repel",
    "Super Repel",
    "Max Repel",
    "Lure",
    "Super Lure",
    "Max Lure",
    "Escape Rope",
    "X Attack",
    "X Defense",
    "X Sp. Atk",
    "X Sp. Def",
    "X Speed",
    "X Accuracy",
    "Dire Hit",
    "Guard Spec.",
    "Poké Doll",
    "Fluffy Tail",
    "Poké Toy",
    "MaxMushrooms",
    "Bottle Cap",
    "GoldBottlCap",
    "Nugget",
    "Big Nugget",
    "Tiny Mushroom",
    "Big Mushroom",
    "Balm Mushroom",
    "Pearl",
    "Big Pearl",
    "Pearl String",
    "Stardust",
    "Star Piece",
    "Comet Shard",
    "Shoal Salt",
    "Shoal Shell",
    "Red Shard",
    "Blue Shard",
    "Yellow Shard",
    "Green Shard",
    "Heart Scale",
    "Honey",
    "Rare Bone",
    "Odd Keystone",
    "PrettyFeather",
    "Relic Copper",
    "Relic Silver",
    "Relic Gold",
    "Relic Vase",
    "Relic Band",
    "Relic Statue",
    "Relic Crown",
    "StrngeSouvnr",
    "Helix Fossil",
    "Dome Fossil",
    "Old Amber",
    "Root Fossil",
    "Claw Fossil",
    "Armor Fossil",
    "Skull Fossil",
    "Cover Fossil",
    "Plume Fossil",
    "Jaw Fossil",
    "Sail Fossil",
    "FosslzedBird",
    "FosslzedFish",
    "FosslzedDrke",
    "FosslzedDino",
    "Growth Mulch",
    "Damp Mulch",
    "Stable Mulch",
    "Gooey Mulch",
    "Rich Mulch",
    "SurprseMulch",
    "Boost Mulch",
    "Amaze Mulch",
    "Red Apricorn",
    "Blue Apricorn",
    "YellwApricorn",
    "GreenApricorn",
    "Pink Apricorn",
    "WhiteApricorn",
    "BlackApricorn",
    "WishingPiece",
    "GalaricaTwig",
    "Armorite Ore",
    "Dynite Ore",
    "Orange Mail",
    "Harbor Mail",
    "Glitter Mail",
    "Mech Mail",
    "Wood Mail",
    "Wave Mail",
    "Bead Mail",
    "Shadow Mail",
    "Tropic Mail",
    "Dream Mail",
    "Fab Mail",
    "Retro Mail",
    "Fire Stone",
    "Water Stone",
    "Thunder Stone",
    "Leaf Stone",
    "Ice Stone",
    "Sun Stone",
    "Moon Stone",
    "Shiny Stone",
    "Dusk Stone",
    "Dawn Stone",
    "Sweet Apple",
    "Tart Apple",
    "Cracked Pot",
    "Chipped Pot",
    "GalaricaCuff",
    "GalrcaWreath",
    "Dragon Scale",
    "Upgrade",
    "Protector",
    "Electirizer",
    "Magmarizer",
    "Dubious Disc",
    "Reaper Cloth",
    "Prism Scale",
    "Whipped Dream",
    "Sachet",
    "Oval Stone",
    "StrwbrySweet",
    "Love Sweet",
    "Berry Sweet",
    "Clover Sweet",
    "Flower Sweet",
    "Star Sweet",
    "Ribbon Sweet",
    "Everstone",
    "Red Nectar",
    "Yellow Nectar",
    "Pink Nectar",
    "Purple Nectar",
    "Flame Plate",
    "Splash Plate",
    "Zap Plate",
    "Meadow Plate",
    "Icicle Plate",
    "Fist Plate",
    "Toxic Plate",
    "Earth Plate",
    "Sky Plate",
    "Mind Plate",
    "Insect Plate",
    "Stone Plate",
    "Spooky Plate",
    "Draco Plate",
    "Dread Plate",
    "Iron Plate",
    "Pixie Plate",
    "Douse Drive",
    "Shock Drive",
    "Burn Drive",
    "Chill Drive",
    "Fire Memory",
    "Water Memory",
    "ElectrcMemory",
    "Grass Memory",
    "Ice Memory",
    "FightngMemory",
    "Poison Memory",
    "Ground Memory",
    "Flying Memory",
    "PsychicMemory",
    "Bug Memory",
    "Rock Memory",
    "Ghost Memory",
    "Dragon Memory",
    "Dark Memory",
    "Steel Memory",
    "Fairy Memory",
    "RustedSword",
    "RustedShield",
    "Red Orb",
    "Blue Orb",
    "Venusaurite",
    "CharizarditeX",
    "CharizarditeY",
    "Blastoisinite",
    "Beedrillite",
    "Pidgeotite",
    "Alakazite",
    "Slowbronite",
    "Gengarite",
    "Kangaskhanite",
    "Pinsirite",
    "Gyaradosite",
    "Aerodactylite",
    "Mewtwonite X",
    "Mewtwonite Y",
    "Ampharosite",
    "Steelixite",
    "Scizorite",
    "Heracronite",
    "Houndoominite",
    "Tyranitarite",
    "Sceptilite",
    "Blazikenite",
    "Swampertite",
    "Gardevoirite",
    "Sablenite",
    "Mawilite",
    "Aggronite",
    "Medichamite",
    "Manectite",
    "Sharpedonite",
    "Cameruptite",
    "Altarianite",
    "Banettite",
    "Absolite",
    "Glalitite",
    "Salamencite",
    "Metagrossite",
    "Latiasite",
    "Latiosite",
    "Lopunnite",
    "Garchompite",
    "Lucarionite",
    "Abomasite",
    "Galladite",
    "Audinite",
    "Diancite",
    "Normal Gem",
    "Fire Gem",
    "Water Gem",
    "Electric Gem",
    "Grass Gem",
    "Ice Gem",
    "Fighting Gem",
    "Poison Gem",
    "Ground Gem",
    "Flying Gem",
    "Psychic Gem",
    "Bug Gem",
    "Rock Gem",
    "Ghost Gem",
    "Dragon Gem",
    "Dark Gem",
    "Steel Gem",
    "Fairy Gem",
    "Normalium Z",
    "Firium Z",
    "Waterium Z",
    "Electrium Z",
    "Grassium Z",
    "Icium Z",
    "Fightinium Z",
    "Poisonium Z",
    "Groundium Z",
    "Flyinium Z",
    "Psychium Z",
    "Buginium Z",
    "Rockium Z",
    "Ghostium Z",
    "Dragonium Z",
    "Darkinium Z",
    "Steelium Z",
    "Fairium Z",
    "Pikanium Z",
    "Eevium Z",
    "Snorlium Z",
    "Mewnium Z",
    "Decidium Z",
    "Incinium Z",
    "Primarium Z",
    "Lycanium Z",
    "Mimikium Z",
    "Kommonium Z",
    "Tapunium Z",
    "Solganium Z",
    "Lunalium Z",
    "Marshadium Z",
    "Aloraichium Z",
    "Pikashunium Z",
    "U-Necrozium Z",
    "Light Ball",
    "Leek",
    "Thick Club",
    "Lucky Punch",
    "Metal Powder",
    "Quick Powder",
    "DeepSeaScale",
    "DeepSeaTooth",
    "Soul Dew",
    "Adamant Orb",
    "Lustrous Orb",
    "Griseous Orb",
    "Sea Incense",
    "Lax Incense",
    "Odd Incense",
    "Rock Incense",
    "Full Incense",
    "Wave Incense",
    "Rose Incense",
    "Luck Incense",
    "Pure Incense",
    "Red Scarf",
    "Blue Scarf",
    "Pink Scarf",
    "Green Scarf",
    "Yellow Scarf",
    "Macho Brace",
    "Power Weight",
    "Power Bracer",
    "Power Belt",
    "Power Lens",
    "Power Band",
    "Power Anklet",
    "Silk Scarf",
    "Charcoal",
    "Mystic Water",
    "Magnet",
    "Miracle Seed",
    "Never-MeltIce",
    "Black Belt",
    "Poison Barb",
    "Soft Sand",
    "Sharp Beak",
    "Twisted Spoon",
    "Silver Powder",
    "Hard Stone",
    "Spell Tag",
    "Dragon Fang",
    "Black Glasses",
    "Metal Coat",
    "Choice Band",
    "Choice Specs",
    "Choice Scarf",
    "Flame Orb",
    "Toxic Orb",
    "Damp Rock",
    "Heat Rock",
    "Smooth Rock",
    "Icy Rock",
    "Electric Seed",
    "Psychic Seed",
    "Misty Seed",
    "Grassy Seed",
    "Absorb Bulb",
    "Cell Battery",
    "Luminous Moss",
    "Snowball",
    "Bright Powder",
    "White Herb",
    "Exp. Share",
    "Quick Claw",
    "Soothe Bell",
    "Mental Herb",
    "King's Rock",
    "Amulet Coin",
    "Cleanse Tag",
    "Smoke Ball",
    "Focus Band",
    "Lucky Egg",
    "Scope Lens",
    "Leftovers",
    "Shell Bell",
    "Wide Lens",
    "Muscle Band",
    "Wise Glasses",
    "Expert Belt",
    "Light Clay",
    "Life Orb",
    "Power Herb",
    "Focus Sash",
    "Zoom Lens",
    "Metronome",
    "Iron Ball",
    "Lagging Tail",
    "Destiny Knot",
    "Black Sludge",
    "Grip Claw",
    "Sticky Barb",
    "Shed Shell",
    "Big Root",
    "Razor Claw",
    "Razor Fang",
    "Eviolite",
    "Float Stone",
    "Rocky Helmet",
    "Air Balloon",
    "Red Card",
    "Ring Target",
    "Binding Band",
    "Eject Button",
    "WeaknssPolicy",
    "Assault Vest",
    "SafetyGoggles",
    "AdrenalineOrb",
    "TerainExtendr",
    "ProtectvePads",
    "Throat Spray",
    "Eject Pack",
    "Heavy-DtyBts",
    "BlundrPolicy",
    "Room Service",
    "UtltyUmbrlla",
    "Cheri Berry",
    "Chesto Berry",
    "Pecha Berry",
    "Rawst Berry",
    "Aspear Berry",
    "Leppa Berry",
    "Oran Berry",
    "Persim Berry",
    "Lum Berry",
    "Sitrus Berry",
    "Figy Berry",
    "Wiki Berry",
    "Mago Berry",
    "Aguav Berry",
    "Iapapa Berry",
    "Razz Berry",
    "Bluk Berry",
    "Nanab Berry",
    "Wepear Berry",
    "Pinap Berry",
    "Pomeg Berry",
    "Kelpsy Berry",
    "Qualot Berry",
    "Hondew Berry",
    "Grepa Berry",
    "Tamato Berry",
    "Cornn Berry",
    "Magost Berry",
    "Rabuta Berry",
    "Nomel Berry",
    "Spelon Berry",
    "Pamtre Berry",
    "Watmel Berry",
    "Durin Berry",
    "Belue Berry",
    "Chilan Berry",
    "Occa Berry",
    "Passho Berry",
    "Wacan Berry",
    "Rindo Berry",
    "Yache Berry",
    "Chople Berry",
    "Kebia Berry",
    "Shuca Berry",
    "Coba Berry",
    "Payapa Berry",
    "Tanga Berry",
    "Charti Berry",
    "Kasib Berry",
    "Haban Berry",
    "Colbur Berry",
    "Babiri Berry",
    "Roseli Berry",
    "Liechi Berry",
    "Ganlon Berry",
    "Salac Berry",
    "Petaya Berry",
    "Apicot Berry",
    "Lansat Berry",
    "Starf Berry",
    "Enigma Berry",
    "Micle Berry",
    "Custap Berry",
    "Jaboca Berry",
    "Rowap Berry",
    "Kee Berry",
    "Maranga Berry",
    "Enigma Berry",
    "TM01",
    "TM02",
    "TM03",
    "TM04",
    "TM05",
    "TM06",
    "TM07",
    "TM08",
    "TM09",
    "TM10",
    "TM11",
    "TM12",
    "TM13",
    "TM14",
    "TM15",
    "TM16",
    "TM17",
    "TM18",
    "TM19",
    "TM20",
    "TM21",
    "TM22",
    "TM23",
    "TM24",
    "TM25",
    "TM26",
    "TM27",
    "TM28",
    "TM29",
    "TM30",
    "TM31",
    "TM32",
    "TM33",
    "TM34",
    "TM35",
    "TM36",
    "TM37",
    "TM38",
    "TM39",
    "TM40",
    "TM41",
    "TM42",
    "TM43",
    "TM44",
    "TM45",
    "TM46",
    "TM47",
    "TM48",
    "TM49",
    "TM50",
    "TM51",
    "TM52",
    "TM53",
    "TM54",
    "TM55",
    "TM56",
    "TM57",
    "TM58",
    "TM59",
    "TM60",
    "TM61",
    "TM62",
    "TM63",
    "TM64",
    "TM65",
    "TM66",
    "TM67",
    "TM68",
    "TM69",
    "TM70",
    "TM71",
    "TM72",
    "TM73",
    "TM74",
    "TM75",
    "TM76",
    "TM77",
    "TM78",
    "TM79",
    "TM80",
    "TM81",
    "TM82",
    "TM83",
    "TM84",
    "TM85",
    "TM86",
    "TM87",
    "TM88",
    "TM89",
    "TM90",
    "TM91",
    "TM92",
    "TM93",
    "TM94",
    "TM95",
    "TM96",
    "TM97",
    "TM98",
    "TM99",
    "TM100",
    "HM01",
    "HM02",
    "HM03",
    "HM04",
    "HM05",
    "HM06",
    "HM07",
    "HM08",
    "Oval Charm",
    "Shiny Charm",
    "CatchngCharm",
    "Exp. Charm",
    "RotomCatalog",
    "Gracidea",
    "Reveal Glass",
    "DNA Splicers",
    "Zygarde Cube",
    "Prison Bottle",
    "N-Solarizer",
    "N-Lunarizer",
    "ReinsOfUnity",
    "Mega Ring",
    "Z-Power Ring",
    "Dynamax Band",
    "Bicycle",
    "Mach Bike",
    "Acro Bike",
    "Old Rod",
    "Good Rod",
    "Super Rod",
    "Dowsing MCHN",
    "Town Map",
    "Vs. Seeker",
    "TM Case",
    "Berry Pouch",
    "\pk\mn Box Link",
    "Coin Case",
    "Powder Jar",
    "Wailmer Pail",
    "Poké Radar",
    "\Po\Ke\Bl\Lo\Ck Case",
    "Soot Sack",
    "Poké Flute",
    "Fame Checker",
    "Teachy TV",
    "S.S. Ticket",
    "Eon Ticket",
    "Mystic Ticket",
    "Aurora Ticket",
    "Old Sea Map",
    "Letter",
    "Devon Parts",
    "Go-Goggles",
    "Devon Scope",
    "Basement Key",
    "Scanner",
    "Storage Key",
    "Key to Room 1",
    "Key to Room 2",
    "Key to Room 4",
    "Key to Room 6",
    "Meteorite",
    "Magma Emblem",
    "Contest Pass",
    "Parcel",
    "Secret Key",
    "Bike Voucher",
    "Gold Teeth",
    "Card Key",
    "Lift Key",
    "Silph Scope",
    "Tri-Pass",
    "Rainbow Pass",
    "Tea",
    "Ruby",
    "Sapphire",
    "AbilityShield",
    "Clear Amulet",
    "PunchingGlove",
    "Covert Cloak",
    "Loaded Dice",
    "AuspciousArmr",
    "BoosterEnergy",
    "BigBmbooShoot",
    "GimighoulCoin",
    "Leader'sCrest",
    "MaliciousArmr",
    "Mirror Herb",
    "ScrllOfDrknss",
    "ScrollOfWatrs",
    "Tera Orb",
    "TinyBmbooShot",
    "Bug TeraShard",
    "DarkTeraShard",
    "DragnTeraShrd",
    "EltrcTeraShrd",
    "FairyTeraShrd",
    "FghtngTerShrd",
    "FireTeraShard",
    "FlyngTeraShrd",
    "GhostTeraShrd",
    "GrassTeraShrd",
    "GrondTeraShrd",
    "Ice TeraShard",
    "NormlTeraShrd",
    "PoisnTeraShrd",
    "PschcTeraShrd",
    "RockTeraShard",
    "SteelTeraShrd",
    "WaterTeraShrd",
    "AdamantCrystl",
    "Griseous Core",
    "LustrousGlobe",
    "BlackAugurite",
    "Linking Cord",
    "Peat Block",
    "Berserk Gene",
    "Fairy Feather",
    "Syrupy Apple",
    "UnrmkblTeacup",
    "MstrpceTeacup",
    "CornrstneMask",
    "WellsprngMask",
    "HrthflameMask",
    "Health Mochi",
    "Muscle Mochi",
    "Resist Mochi",
    "Genius Mochi",
    "Clever Mochi",
    "Swift Mochi",
    "FrshStrtMochi",
    "GlmmringCharm",
    "Metal Alloy",
    "StllrTeraShrd",
    "JublifeMuffin",
    "Remedy",
    "Fine Remedy",
    "Superb Remedy",
    "Aux Evasion",
    "Aux Guard",
    "Aux Power",
    "AuxPowerguard",
    "ChoiceDumplng",
    "Swap Snack",
    "2xSpicedRadsh",
    "Pokéshi Doll"
]
var output = '';
var output2 = '';
var output3 = '';
var output4 = '';
var output5 = '';
var output6 = '';
var output7 = '';
for (const mon of mons) {
    var hpev = 0;
    var atkev = 0;
    var defev = 0;
    var speev = 0;
    var spaev = 0;
    var spdev = 0;
    if (HMAJSON[mon].evs) {
        hpev = HMAJSON[mon].evs.hp;
        atkev = HMAJSON[mon].evs.atk;
        defev = HMAJSON[mon].evs.def;
        speev = HMAJSON[mon].evs.spe;
        spaev = HMAJSON[mon].evs.spa;
        spdev = HMAJSON[mon].evs.spd;
    };
    var itemcommon = HMAJSON[mon].itemcommon;
    if (!gens.get(3).items.get(itemcommon)) itemcommon = '????????';
    var itemrare = HMAJSON[mon].itemrare;
    if (!gens.get(3).items.get(itemrare)) itemrare = '????????';
    var ability1 = HMAJSON[mon].ability1;
    if (!gens.get(3).abilities.get(ability1)) ability1 = '-------';
    var ability2 = HMAJSON[mon].ability2;
    if (!gens.get(3).abilities.get(ability2)) ability2 = '-------';
    var friendship = HMAJSON[mon].friendship;
    if (friendship == 50) friendship = 70;
    var expyield = HMAJSON[mon].expyield;
    if (expyield > 255) expyield = 255;
    output += HMAJSON[mon].hp + ', ' + HMAJSON[mon].attack + ', ' + HMAJSON[mon].defense + ', ' + HMAJSON[mon].speed + ', ' + HMAJSON[mon].spatk + ', ' + HMAJSON[mon].spdef + ', ' + HMAJSON[mon].type1 + ', ' + HMAJSON[mon].type2 + ', ' + HMAJSON[mon].catchrate + ', ' + expyield + ', (' + hpev + ', ' + atkev + ', ' + defev + ', ' + speev + ', ' + spaev + ', ' + spdev + '), "' + itemcommon + '", "' + itemrare + '", "' + HMAJSON[mon].genderratio + '", ' + HMAJSON[mon].eggcycles + ', ' + friendship + ', "' + HMAJSON[mon].growthrate + '", "' + HMAJSON[mon].egggroup1 + '", "' + HMAJSON[mon].egggroup2 + '", "' + ability1 + '", "' + ability2 + '", ' + HMAJSON[mon].safarizonefleerate + ', (Red false), 0\n';
    if (HMAJSON[mon].iconpal) output2 += HMAJSON[mon].iconpal.index + ', ';
    else output2 += 0 + ', ';
    for (const move of movetutormoves) {
        const movename = gens.get(3).moves.get(move).name;
        if (HMAJSON[mon].teachablelearnset && HMAJSON[mon].teachablelearnset.includes(movename)) output3 += '"' + movename.replace('Soft-Boiled', 'Softboiled') + '" ';
    }
    output3 += '/\n';
    for (const move of tms) {
        const movename = gens.get(3).moves.get(move).name;
        if (HMAJSON[mon].teachablelearnset && HMAJSON[mon].teachablelearnset.includes(movename)) output4 += '"' + movename.replace('Solar Beam', 'Solarbeam') + '" ';
    }
    output4 += '/\n';
    if (HMAJSON[mon].leveluplearnset) {
        output5 += '@{ '
        for (const movename in HMAJSON[mon].leveluplearnset) {
            if (!gens.get(3).moves.get(movename)) continue;
            const level = HMAJSON[mon].leveluplearnset[movename];
            output5 += '+"' + movename.replace('Soft-Boiled', 'Softboiled').replace('Solar Beam', 'Solarbeam').replace('Ancient Power', 'Ancientpower').replace('Bubble Beam', 'Bubblebeam').replace('Double Slap', 'Doubleslap').replace('Dragon Breath', 'Dragonbreath').replace('Dynamic Punch', 'Dynamicpunch').replace('Extreme Speed', 'Extremespeed').replace('Feint Attack', 'Faint Attack').replace('Feather Dance', 'Featherdance').replace('Grass Whistle', 'Grasswhistle').replace('High Jump Kick', 'Hi Jump Kick').replace('Poison Powder', 'Poisonpowder').replace('Sand Attack', 'Sand-Attack').replace('Self-Destruct', 'Selfdestruct').replace('Smelling Salts', 'Smellingsalt').replace('Sonic Boom', 'Sonicboom').replace('Thunder Punch', 'Thunderpunch').replace('Thunder Shock', 'Thundershock').replace('Vise Grip', 'Vicegrip') + '", ' + level + '\n';
        }
        output5 += '[] @}\n';
    }
    else output5 += '@{ [] @}\n';
    if (HMAJSON[mon].eggmoves && HMAJSON[mon].eggmoves.length > 0) {
        output6 += '[' + mon + ']\n'
        for (var movename of HMAJSON[mon].eggmoves) {
            if (!gens.get(3).moves.get(toID(movename))) continue;
            movename = gens.get(3).moves.get(toID(movename)).name;
            output6 += movename.replace('Soft-Boiled', 'Softboiled').replace('Solar Beam', 'Solarbeam').replace('Ancient Power', 'Ancientpower').replace('Bubble Beam', 'Bubblebeam').replace('Double Slap', 'Doubleslap').replace('Dragon Breath', 'Dragonbreath').replace('Dynamic Punch', 'Dynamicpunch').replace('Extreme Speed', 'Extremespeed').replace('Feint Attack', 'Faint Attack').replace('Feather Dance', 'Featherdance').replace('Grass Whistle', 'Grasswhistle').replace('High Jump Kick', 'Hi Jump Kick').replace('Poison Powder', 'Poisonpowder').replace('Sand Attack', 'Sand-Attack').replace('Self-Destruct', 'Selfdestruct').replace('Smelling Salts', 'Smellingsalt').replace('Sonic Boom', 'Sonicboom').replace('Thunder Punch', 'Thunderpunch').replace('Thunder Shock', 'Thundershock').replace('Vise Grip', 'Vicegrip') + '\n';
        }
    }
    if (HMAJSON[mon].evolutions) {
        counter = 0;
        for (const evo in HMAJSON[mon].evolutions) {
            if (counter > 4) continue;
            for (const method in HMAJSON[mon].evolutions[evo]) {
                var param = HMAJSON[mon].evolutions[evo][method];
                if (method == 'EVO_ITEM') {
                    param = '"' + items[param] + '"';
                    if (!gens.get(3).items.get(param)) param = '????????';
                }
                if (counter < 4) output7 += method + ', ' + param + ', ' + evo + ', ' + 0 + ', ';
                else output7 += method + ', ' + param + ', ' + evo + ', ' + 0 + '\n';
                counter++;
            }
        }
        for (var i = counter; i < 5; i++) {
            if (i < 4) output7 += 'None, 0, ??????????, 0, ';
            else output7 += 'None, 0, ??????????, 0\n';
        }
    }
}
fs.writeFileSync('output.txt', output);
fs.writeFileSync('output2.txt', output2);
fs.writeFileSync('output3.txt', output3);
fs.writeFileSync('output4.txt', output4);
fs.writeFileSync('output5.txt', output5);
fs.writeFileSync('output6.txt', output6);
fs.writeFileSync('output7.txt', output7);